### ISSUE TITLE
connected compoenents inside overdrive

### ISSUE THREAD

**Issue by arunkjn** [berzniz/react-overdrive#6]
If connected components are used inside overdrive, they do not receive store reference and throw an error

**Comment by berzniz** [comment]
Can you provide a basic example? I have it working in a react/redux setup without seeing the issue.

**Comment by arunkjn** [comment]
I will try to replicate it in a fiddle

**Comment by green-arrow** [comment]
@berzniz - If it helps any, it looks like an issue with the context of the children not being preserved. I have children of the `Overdrive` component at various layers that use `context` for theming purposes, and any time the overdrive component animates, non of the children components are able to get the prop they need off of context and an error is thrown saying it's undefined.

I'm not sure why this is happening, since everything I'm reading says that `React.cloneElement` should preserve context properly in React 0.14 and up.

**Comment by berzniz** [comment]
@green-arrow is it breaking while animating? or even before that?

The animation happens on a different `ReactDOM.render` tree, so I can see why the `context` might not transfer there. I'll try to see if we can clone that as well.

**Comment by green-arrow** [comment]
@berzniz to be honest I can't really tell when it happens. As soon as I reorder some items, they automatically move to the new position (no animation) and I get a console error about the context.

I think the animation not happening is probably an issue on my end, but not sure.

**Comment by berzniz** [comment]
Thanks @Anujan for providing the fix. It's merged but due to some git magic, the contribution was squashed and your name is not in the contributors list. Sorry.

**Comment by green-arrow** [comment]
Thanks @arunkjn and @berzniz, that worked wonderfully.
